//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modson.ModsonDatabaseAccessorService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/ModsonService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ModsonDatabaseAccessorService.IModsonDatabaseAccessorService")]
    public interface IModsonDatabaseAccessorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModsonDatabaseAccessorService/GetData", ReplyAction="http://tempuri.org/IModsonDatabaseAccessorService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModsonDatabaseAccessorService/GetData", ReplyAction="http://tempuri.org/IModsonDatabaseAccessorService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModsonDatabaseAccessorService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IModsonDatabaseAccessorService/GetDataUsingDataContractRespons" +
            "e")]
        Modson.ModsonDatabaseAccessorService.CompositeType GetDataUsingDataContract(Modson.ModsonDatabaseAccessorService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModsonDatabaseAccessorService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IModsonDatabaseAccessorService/GetDataUsingDataContractRespons" +
            "e")]
        System.Threading.Tasks.Task<Modson.ModsonDatabaseAccessorService.CompositeType> GetDataUsingDataContractAsync(Modson.ModsonDatabaseAccessorService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModsonDatabaseAccessorService/GetUsers", ReplyAction="http://tempuri.org/IModsonDatabaseAccessorService/GetUsersResponse")]
        string GetUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModsonDatabaseAccessorService/GetUsers", ReplyAction="http://tempuri.org/IModsonDatabaseAccessorService/GetUsersResponse")]
        System.Threading.Tasks.Task<string> GetUsersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IModsonDatabaseAccessorServiceChannel : Modson.ModsonDatabaseAccessorService.IModsonDatabaseAccessorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ModsonDatabaseAccessorServiceClient : System.ServiceModel.ClientBase<Modson.ModsonDatabaseAccessorService.IModsonDatabaseAccessorService>, Modson.ModsonDatabaseAccessorService.IModsonDatabaseAccessorService {
        
        public ModsonDatabaseAccessorServiceClient() {
        }
        
        public ModsonDatabaseAccessorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ModsonDatabaseAccessorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModsonDatabaseAccessorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModsonDatabaseAccessorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public Modson.ModsonDatabaseAccessorService.CompositeType GetDataUsingDataContract(Modson.ModsonDatabaseAccessorService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<Modson.ModsonDatabaseAccessorService.CompositeType> GetDataUsingDataContractAsync(Modson.ModsonDatabaseAccessorService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public string GetUsers() {
            return base.Channel.GetUsers();
        }
        
        public System.Threading.Tasks.Task<string> GetUsersAsync() {
            return base.Channel.GetUsersAsync();
        }
    }
}
